/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    // val greeting: String
    //     get() {
    //         return "Hello World!"
    //     }

    external fun helloFromC(name: String): String;

    companion object {
        init {
            System.loadLibrary("testjni");
        }
    }
}


