/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.assert
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.helloFromC("Gix"), "app should return string")
    }

    @Test
    fun appReturnNativeHelloFromC() {
        val classUnderTest = App()
        assert(classUnderTest.helloFromC("Gix") == "Hello Gix")
    }
}
